### ISSUE TITLE
[BUG] Component Checkbox : return false when it's checked

### ISSUE THREAD

**Issue by cnavarro-prestashop** [PrestaShopCorp/puik#195]
# Context

There's an issue about Checkbox component : when the checkbox is checked, the value return is false

# Reproduce link

Ask to @luctst 

# Steps to Reproduce

Ask to @luctst 

# Expected Behavior

When the checkbox is checked it should return true

# Current Behavior

when the checkbox is checked, the value return is false

# Additional comments

Blocking for @luctst squad

**Comment by PoulainMaxime** [comment]
After some investigation, we realized that it was a problem with the v-model used to declare the checked attribute on the radio button. So I think we can close this ticket, my bad :sweat_smile:!
