### ISSUE TITLE
[BUG] Select component options style issue

### ISSUE THREAD

**Issue by PoulainMaxime** [PrestaShopCorp/puik#198]
# Context

The component `puik-select` has an unexpected behavior, when the full-width property is set to true, the options and the checked logo have a style problem.

Puik version 1.5.4

# Reproduce link
https://main--6267e986619a13004a943d93.chromatic.com/?path=/story/components-select--default the storybook from the production

# Steps to Reproduce
The issue not working only on the select searchable & select max-content

# Expected Behavior
![Screenshot 2023-09-20 at 16 06 08](https://github.com/PrestaShopCorp/puik/assets/22856724/e706585f-c7df-48db-b576-153142bab1ca)

# Current Behavior
![Screenshot 2023-09-20 at 16 02 35](https://github.com/PrestaShopCorp/puik/assets/22856724/86d53bc7-f5e6-444d-b3dc-be7686f38b01)

# Additional comments
Inside the story, the code template provided for maxContentOption doesn't include all parameters that reflect the component https://github.com/PrestaShopCorp/puik/blob/a3618c5564ed66328563c498c9aae2ca8c1ef0eb/packages/components/select/stories/select.stories.ts#L704

**Comment by MikeLebeau** [comment]
Fixed in the PR #234 \o/
