### ISSUE TITLE
[BUG] puik link decoration underline is fucked up on multi-line 😭 + width 100% not good

### ISSUE THREAD

**Issue by MikeLebeau** [PrestaShopCorp/puik#232]
# Context

Le 'underline' ne s'affiche pas si le texte est sur plusieurs ligne + la width a 100% pose probleme si j'ai un lien dans un flex-col par exemple, jte mets un ptit screen plus bas

* Browser: Chrome
* Vue version: 3.3.4
* Package version: 1.6.1
* Node version: 20.1
* NPM Version: 9.6.4
* PNPM Version: 8.6.3
* Configuration used: 🤔 

Dans ce screen on voit que les liens sur une seule ligne sont nickel mais le lien `Prestashop integration documentation.` a la fin du petit paragraphe de description n'a pas de 'underline'

![image](https://github.com/PrestaShopCorp/puik/assets/13118263/4c632559-06b6-4cf3-b33e-07e5b4670184)

Soucis de width
![image](https://github.com/PrestaShopCorp/puik/assets/13118263/f34c671f-5a9a-4e04-80ff-6a9a6bbf4a8c)

# Reproduce link

# Steps to Reproduce

# Expected Behavior

# Current Behavior

# Additional comments

**Comment by mattgoud** [comment]
ah ! ok je vais regarder, peut-être un nowrap pour les links afin d'éviter ce souci.

**Comment by mattgoud** [comment]
> ah ! ok je vais regarder @MikeLebeau , peut-être un nowrap pour les links afin d'éviter ce souci.

@MikeLebeau  en fait le nowrap était une mauvaise idée, j'ai utilisé un background image dans la PR pour créer l'underline. ça permet de garder la possibilité de revenir à la ligne et y'a plus le souci du width par la même occasion.
