### ISSUE TITLE
[BUG] [Pagination][Large] Items per page select

### ISSUE THREAD

**Issue by ThbPS** [PrestaShopCorp/puik#275]
### Expected Behavior

Items per page select should be hidden on large screen when ```itemsPerPageOptions``` prop is not provided. This prop should be optional.

It should follow design system guidelines:
![image](https://github.com/PrestaShopCorp/puik/assets/109082310/9724ca17-d3a8-4ee8-b9d6-fe6bd8cc4c8e)

https://www.figma.com/file/YxI7gWKwOKc0QGMvaTal8j/PrestaShop-Design-Kit?type=design&node-id=21872-116513&mode=design&t=u9u3nzGHseemG0hm-4

![image](https://github.com/PrestaShopCorp/puik/assets/109082310/2eb0300b-a529-40f3-a1c3-8cde88f27b0c)
https://www.figma.com/file/J6CHwMqeancMAolHzNhcvO/Validation?type=design&node-id=700-36055&mode=design&t=1i6nF18oqM2xeVVd-4

### Current Behavior

Items per page select is displayed when ```itemsPerPageOptions``` is not provided.

![image](https://github.com/PrestaShopCorp/puik/assets/109082310/8f669328-ef29-4d71-81ca-9fb5a8369bd7)
https://uikit.prestashop.com/?path=/story/components-pagination--large

**Comment by kktos** [comment]
Also, something was lost in translation.
With puik, we have:
![image](https://github.com/PrestaShopCorp/puik/assets/1190639/941a47dd-d6fa-4def-957a-bc2ff6e7bccb)
And in the Design System, we have:
![image](https://github.com/PrestaShopCorp/puik/assets/1190639/d57cf024-df9a-41a0-8ff0-eec70ac3ba02)

Puik is missing the label "items per page", which is key to understand the second input number !

**Comment by mattgoud** [comment]
> Also, something was lost in translation. With puik, we have: ![image](https://private-user-images.githubusercontent.com/1190639/289895948-941a47dd-d6fa-4def-957a-bc2ff6e7bccb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTUyMzUsIm5iZiI6MTcxOTIxNDkzNSwicGF0aCI6Ii8xMTkwNjM5LzI4OTg5NTk0OC05NDFhNDdkZC1kNmZhLTRkZWYtOTU3YS1iYzJmZjZlN2JjY2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMDc0MjE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGYzYjA0ZjhkNDhiNWIyYzU3MWQ0NTAwZjFmODlmZmRjYTExNGZiNjdiZmViOWQxYTZkMDAzNDZmYjFhZDk2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._vKtwco-CLha1nkK6yzgztxZ9fNO4KYSfDiuIsIFEIo) And in the Design System, we have: ![image](https://private-user-images.githubusercontent.com/1190639/289896098-d57cf024-df9a-41a0-8ff0-eec70ac3ba02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTUyMzUsIm5iZiI6MTcxOTIxNDkzNSwicGF0aCI6Ii8xMTkwNjM5LzI4OTg5NjA5OC1kNTdjZjAyNC1kZjlhLTQxYTAtOGZmMC1lZWM3MGFjM2JhMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMDc0MjE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDBkMmM1YmI1NmQ0MmVmZjZkNjhhNDE3YmE1ZWVmZWRjMWY0ZjM5MTgyYmRlYzlhZmM5MmIwZWE1ZGUyYzFkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PTYlak6MMQLS_J3WO9V8IhowyLQX69hJ0z79DwqH828)
> 
> Puik is missing the label "items per page", which is key to understand the second input number !

ok @kktos the label has been added (see https://github.com/PrestaShopCorp/puik/pull/349)

**Comment by mattgoud** [comment]
> Last but not least, in order to localized the text (for instance, "500 results") the property label could be used. But, it will replace the whole text, that is "500 results". So if you wished to have a french version with "500 résultats" and you have label:"résultats" you won't get what you expected, you'll get only "résultats".

Tested using PuikConfigProvider (PR in progress for the use of this component [here](https://github.com/PrestaShopCorp/puik/pull/351)) and normally the translation works

**Comment by mattgoud** [comment]
> ### Expected Behavior
> Items per page select should be hidden on large screen when `itemsPerPageOptions` prop is not provided. This prop should be optional.
> 
> It should follow design system guidelines: ![image](https://private-user-images.githubusercontent.com/109082310/289895707-9724ca17-d3a8-4ee8-b9d6-fe6bd8cc4c8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTU5OTQsIm5iZiI6MTcxOTIxNTY5NCwicGF0aCI6Ii8xMDkwODIzMTAvMjg5ODk1NzA3LTk3MjRjYTE3LWQzYTgtNGVlOC1iOWQ2LWZlNmJkOGNjNGM4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwNzU0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Njk4YWRiM2YyMTM5NGRkYzA2MmQ2MWMzZjhiNzJiNmFkZjE0YTM1Y2E0ODU3NGY3MjFiMGI0NTllZGQwMDM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6-sh3gHSbTrMhUm3sgDma3fRHWjMNsY6vfTARk2Dmak)
> 
> https://www.figma.com/file/YxI7gWKwOKc0QGMvaTal8j/PrestaShop-Design-Kit?type=design&node-id=21872-116513&mode=design&t=u9u3nzGHseemG0hm-4
> 
> ![image](https://private-user-images.githubusercontent.com/109082310/289886333-2eb0300b-a529-40f3-a1c3-8cde88f27b0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTU5OTQsIm5iZiI6MTcxOTIxNTY5NCwicGF0aCI6Ii8xMDkwODIzMTAvMjg5ODg2MzMzLTJlYjAzMDBiLWE1MjktNDBmMy1hMWMzLThjZGU4OGYyN2IwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwNzU0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWZkNGVmYTQ2ZGI4OGI1NTBhN2NhOTY5ZmQ2MDM2NjU0ZGM0NDAyZmFjZjgzNzk4NjdiYjU0YzAwNTZkMjFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xgMlDV2j7mWyNxh9G2aR-Yj--YyoD_x4nQlp2W8Ns6o) https://www.figma.com/file/J6CHwMqeancMAolHzNhcvO/Validation?type=design&node-id=700-36055&mode=design&t=1i6nF18oqM2xeVVd-4
> 
> ### Current Behavior
> Items per page select is displayed when `itemsPerPageOptions` is not provided.
> 
> ![image](https://private-user-images.githubusercontent.com/109082310/289886620-8f669328-ef29-4d71-81ca-9fb5a8369bd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTU5OTQsIm5iZiI6MTcxOTIxNTY5NCwicGF0aCI6Ii8xMDkwODIzMTAvMjg5ODg2NjIwLThmNjY5MzI4LWVmMjktNGQ3MS04MWNhLTlmYjVhODM2OWJkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwNzU0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDJjZGY3ODAxZjBkN2Y3YjgwODJiZWJkNDYyODc5ZmVkMWYwMzgyMjhkMzdkNjc0ZjVmNGJjZWM0Yjc5MzFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tGV0GwUytX0k_-3qDkFCWgVgNXLLLP-cNcMPAuVTt_I) https://uikit.prestashop.com/?path=/story/components-pagination--large

ok @ThbPS 2 new props created for displaying or not these elements (displayItemsPerPage and displayResults)
